# Generated by Django 4.2.5 on 2023-09-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'agendamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'categoriaservicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoriataller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='TDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('abreviatura', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tdocumento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TPEmpresario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tpempresario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('foto', models.CharField(max_length=255)),
                ('contrato', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.contrato')),
                ('municipio', models.ForeignKey(db_column='municipio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.municipio')),
                ('tdocumento', models.ForeignKey(db_column='tdocumento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tdocumento')),
                ('tpempresario', models.ForeignKey(db_column='tpempresario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.tpempresario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('categoriaservicio', models.ForeignKey(db_column='categoriaservicio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoriaservicio')),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('agendamiento', models.ForeignKey(db_column='agendamiento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.agendamiento')),
            ],
        ),
        migrations.CreateModel(
            name='FacCabeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor_unitario', models.IntegerField(blank=True, null=True)),
                ('valortotal', models.IntegerField(blank=True, null=True)),
                ('pagos_tarjetacredito', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario')),
            ],
            options={
                'db_table': 'faccabeza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('razonsocial', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('categoriataller', models.ForeignKey(db_column='categoriataller_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.categoriataller')),
                ('municipio', models.ForeignKey(db_column='municipio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.municipio')),
            ],
            options={
                'db_table': 'empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuerpoFacrura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('valorunitariol', models.IntegerField(blank=True, null=True)),
                ('valortotal', models.IntegerField(blank=True, null=True)),
                ('scripcion_idscripcion', models.IntegerField(blank=True, null=True)),
                ('faccabeza', models.ForeignKey(db_column='faccabeza_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.faccabeza')),
            ],
            options={
                'db_table': 'cuerpofacrura',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='categoriataller',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.servicio'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.servicio'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuario'),
        ),
    ]
